export const subjectData: {
  [SemCourse: string]: { [Subject: string]: number };
} = {
  "1-CSE-PHY": {
    "Computational Mathematics - 1": 4,
    "Applied Physics for Engineers": 3,
    "Fundamentals of Electronics": 3,
    "Programming for Problem Solving": 3,
    "Fundamentals of Mechanical Engineering": 3,
    "Communication Skills in English": 2,
    "Workshop Practice": 1,
    "Programming for Problem Solving Lab": 1,
  },
  "2-CSE-CHM": {
    "Computational Mathematics - 2": 4,
    "Applied Chemistry for Engineers": 3,
    "Fundamentals of Electrical Engineering": 3,
    "Engineering Mechanics and Smart Buildings": 3,
    "Introduction to Object Oriented Programming": 3,
    "Environmental Studies": 2,
    "Data Visualization": 2,
    "Introduction to Object Oriented Programming Lab": 1,
    "Computer Aided Engineering Graphics": 1,
  },
  "1-CSE-CHM": {
    "Computational Mathematics - 1": 4,
    "Applied Chemistry for Engineers": 3,
    "Fundamentals of Electrical Engineering": 3,
    "Programming for Problem Solving": 3,
    "Environmental Studies": 2,
    "Engineering Mechanics and Smart Buildings": 3,
    "Programming for Problem Solving Lab": 1,
    "Computer Aided Engineering Graphics": 1,
  },
  "2-CSE-PHY": {
    "Computational Mathematics - 2": 4,
    "Applied Physics for Engineers": 3,
    "Fundamentals of Electronics": 3,
    "Fundamentals of Mechanical Engineering": 3,
    "Data Visualisation": 2,
    "Introduction to Object Oriented Programming": 3,
    "Communication Skills in English": 2,
    "Workshop Practice": 1,
    "Introduction to Object Oriented Programming Lab": 1,
  },
  "3-CSE": {
    "Discrete Mathematical Structures": 3,
    "Data Structures": 4,
    "Data Analytics": 4,
    "Digital Systems and Computer Organization": 4,
    "Data Communication and Computer Networks": 4,
    "Data Structures Lab": 1,
    "Digital Systems Lab": 1,
  },
  "4-CSE": {
    "Probability and Optimization": 3,
    "Database Systems": 4,
    "Design & Analysis of Algorithms": 4,
    "Introduction to Artificial Intelligence": 3,
    "Operating Systems": 3,
    "Operating Systems Lab": 1,
    "Database Systems Lab": 2,
    "Object-Oriented Software Development Lab": 2,
  },
  "5-CSE": {
    "Essentials of Management": 3,
    "Principles of Cryptography": 3,
    "Operating Systems": 3,
    "Software Engineering": 3,
    "Computer Networks": 3,
    "Software Engineering Lab": 1,
    "Operating Systems Lab": 1,
    "Computer Networks Lab": 1,
  },
  "6-CSE": {
    "Engineering Economics and Financial Management": 3,
    "Compiler Design": 3,
    "Parallel Computer Architecture and Programming": 3,
    "Parallel Programming Lab": 1,
    "Compiler Design Lab": 1,
    "Web Programming Lab": 1,
    "Program Elective - 1 (Minor Specialization)": 3,
    "Program Elective - 2 (Minor Specialization)": 3,
  },
  "7-CSE": {
    "Program Elective - 3 (Minor Specialization)": 3,
    "Program Elective - 4 (Minor Specialization)": 3,
    "Program Elective - 5": 3,
    "Program Elective - 6": 3,
    "Program Elective - 7": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-CSE": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "B Tech Honors (Theory 1) (5 Semester)": 4,
    "B Tech Honors (Theory 2) (6 Semester)": 4,
    "B Tech Honors (Theory 3) (7 Semester)": 4,
  },
  "1-NONCS-PHY": {
    "Engineering Mathematics - 1": 4,
    "Engineering Physics": 3,
    "Mechanics of Solids": 3,
    "Basic Electronics": 3,
    "Basic Mechanical Engineering": 3,
    "Communication Skills in English": 2,
    "Engineering Physics Lab": 1,
    "Workshop Practice": 1,
    "Engineering Graphics - 1": 1,
  },
  "2-NONCS-CHM": {
    "Engineering Mathematics - 2": 4,
    "Engineering Chemistry": 3,
    "Biology for Engineers": 3,
    "Basic Electrical Technology": 3,
    "Problem Solving Using Computers": 3,
    "Environmental Studies": 2,
    "Engineering Chemistry Lab": 1,
    "Problem Solving Using Computers Lab": 1,
    "Engineering Graphics - 2": 1,
  },
  "1-NONCS-CHM": {
    "Engineering Mathematics - 1": 4,
    "Engineering Chemistry": 3,
    "Biology for Engineers": 3,
    "Basic Electrical Technology": 3,
    "Problem Solving Using Computers": 3,
    "Environmental Studies": 2,
    "Engineering Chemistry Lab": 1,
    "Problem Solving Using Computers Lab": 1,
    "Engineering Graphics - 1": 1,
  },
  "2-NONCS-PHY": {
    "Engineering Mathematics - 2": 4,
    "Engineering Physics": 3,
    "Mechanics of Solids": 3,
    "Basic Electronics": 3,
    "Basic Mechanical Engineering": 3,
    "Communication Skills in English": 2,
    "Engineering Physics Lab": 1,
    "Workshop Practice": 1,
    "Engineering Graphics - 2": 1,
  },
  "3-AIML": {
    "Discrete Mathematical Structures": 3,
    "Data Structures": 4,
    "Data Analytics": 4,
    "Digital Systems and Computer Organization": 4,
    "Data Communication and Computer Networks": 4,
    "Data Structures Lab": 1,
    "Digital Systems Lab": 1,
  },
  "4-AIML": {
    "Probability and Optimization": 3,
    "Database Systems": 4,
    "Design & Analysis of Algorithms": 4,
    "Introduction to Artificial Intelligence": 3,
    "Operating Systems": 3,
    "Operating Systems Lab": 1,
    "Database Systems Lab": 2,
    "Object-Oriented Software Development Lab": 2,
  },
  "5-AIML": {
    "Essentials of Management": 3,
    "Machine Learning": 3,
    "Foundation of Computer Vision": 3,
    "Big Data Analytics": 3,
    "Artificial Neural Network": 3,
    "Computer Vision Lab": 1,
    "Big Data Analytics Lab": 1,
    "Machine Learning Lab": 1,
  },
  "6-AIML": {
    "Engineering Economics and Financial Management": 3,
    "Deep Learning": 3,
    "Parallel Computer Architecture and Programming": 3,
    "Program Elective – I/Minor Specialization": 3,
    "Program Elective – II/ Minor Specialization": 3,
    "Deep Learning Lab": 1,
    "Web Programming Lab": 1,
    "Parallel Programming Lab": 1,
  },
  "7-AIML": {
    "Program Elective – III/ Minor Specialization": 3,
    "Program Elective – IV/ Minor Specialization": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-AIML": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "B Tech Honors (Theory 1) (V Semester)": 4,
    "B Tech Honors (Theory 2) (VI Semester)": 4,
    "B Tech Honors (Theory 3) (VII Semester)": 4,
  },
  "3-IT": {
    "Discrete Mathematical Structures": 3,
    "Data Structures": 4,
    "Data Analytics": 4,
    "Digital Systems and Computer Organization": 4,
    "Data Communication and Computer Networks": 4,
    "Data Structures Lab": 1,
    "Digital Systems Lab": 1,
  },
  "4-IT": {
    "Probability and Optimization": 3,
    "Database Systems": 4,
    "Design & Analysis of Algorithms": 4,
    "Introduction to Artificial Intelligence": 3,
    "Operating Systems": 3,
    "Operating Systems Lab": 1,
    "Database Systems Lab": 2,
    "Object-Oriented Software Development Lab": 2,
  },
  "5-IT": {
    "Essentials of Management": 3,
    "Information Security": 3,
    "Principles of Operating Systems": 4,
    "Software Engineering": 3,
    "Flexible Core - 1 (A1/B1/C1/D1)": 3,
    "Information Security Lab": 1,
    "Principles of Operating Systems Lab": 1,
  },
  "6-IT": {
    "Engineering Economics and Financial Management": 3,
    "Flexible Core - 2 (A2/B2/C2/D2)": 3,
    "Data Mining": 4,
    "Program Elective - I / Minor Specialization": 3,
    "Program Elective - II / Minor Specialization": 3,
    "Advanced Technology Lab": 1,
    "Data Mining Lab": 1,
  },
  "7-IT": {
    "Program Elective - III / Minor Specialization": 3,
    "Program Elective - IV / Minor Specialization": 3,
    "Program Elective - V": 3,
    "Program Elective - VI": 3,
    "Program Elective - VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-IT": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "B Tech Honors (Theory 1) (V Semester)": 4,
    "B Tech Honors (Theory 2) (VI Semester)": 4,
    "B Tech Honors (Theory 3) (VII Semester)": 4,
  },
  "3-CCE": {
    "Discrete Mathematical Structures": 3,
    "Data Structures": 4,
    "Data Analytics": 4,
    "Digital Systems and Computer Organization": 4,
    "Data Communication and Computer Networks": 4,
    "Data Structures Lab": 1,
    "Digital Systems Lab": 1,
  },
  "4-CCE": {
    "Probability and Optimization": 3,
    "Database Systems": 4,
    "Design & Analysis of Algorithms": 4,
    "Introduction to Artificial Intelligence": 3,
    "Operating Systems": 3,
    "Operating Systems Lab": 1,
    "Database Systems Lab": 2,
    "Object-Oriented Software Development Lab": 2,
  },
  "5-CCE": {
    "Essentials of Management": 3,
    "Information Security": 3,
    "Embedded System Design": 3,
    "Wireless Communication and Computing": 4,
    "Flexible Core - 1 (A1/B1/C1)": 3,
    "Information Security Lab": 1,
    "Embedded System Design Lab": 1,
  },
  "6-CCE": {
    "Engineering Economics and Financial Management": 3,
    "Network Programming and Advanced Communication Networks": 3,
    "Flexible Core - 2 (A2/B2/C2)": 3,
    "Program Elective - I / Minor Specialization": 3,
    "Program Elective - II / Minor Specialization": 3,
    "Mobile Application Development Lab": 2,
    "Network Design and Programming Lab": 1,
  },
  "7-CCE": {
    "Program Elective - III / Minor Specialization": 3,
    "Program Elective - IV / Minor Specialization": 3,
    "Program Elective - V": 3,
    "Program Elective - VI": 3,
    "Program Elective - VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-CCE": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "B Tech Honors (Theory 1) (V Semester)": 4,
    "B Tech Honors (Theory 2) (VI Semester)": 4,
    "B Tech Honors (Theory 3) (VII Semester)": 4,
  },
  "3-DSE": {
    "Discrete Mathematical Structures": 3,
    "Data Structures": 4,
    "Data Analytics": 4,
    "Digital Systems and Computer Organization": 4,
    "Data Communication and Computer Networks": 4,
    "Data Structures Lab": 1,
    "Digital Systems Lab": 1,
  },
  "4-DSE": {
    "Probability and Optimization": 3,
    "Database Systems": 4,
    "Design & Analysis of Algorithms": 4,
    "Introduction to Artificial Intelligence": 3,
    "Operating Systems": 3,
    "Operating Systems Lab": 1,
    "Database Systems Lab": 2,
    "Object-Oriented Software Development Lab": 2,
  },
  "5-DSE": {
    "Engineering Economics & Financial Management": 3,
    "Mathematical Foundations for Data Science-III": 3,
    "Operations Research": 3,
    "Deep Learning Techniques": 4,
    "High Performance Computing": 3,
    "Deep Learning Techniques Lab": 1,
    "High Performance Computing Lab": 1,
  },
  "6-DSE": {
    "Essentials of Management": 3,
    "Principles of Artificial Intelligence": 4,
    "Big Data Analytics and Tools": 3,
    "Program Elective - I / Minor Specialization": 3,
    "Program Elective - II / Minor Specialization": 3,
    "Principles of Artificial Intelligence Lab": 1,
    "Big Data Analytics and Tools Lab": 1,
  },
  "7-DSE": {
    "Program Elective - III / Minor Specialization": 3,
    "Program Elective - IV / Minor Specialization": 3,
    "Program Elective - V": 3,
    "Program Elective - VI": 3,
    "Program Elective - VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-DSE": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "B Tech Honors (Theory 1) (V Semester)": 4,
    "B Tech Honors (Theory 2) (VI Semester)": 4,
    "B Tech Honors (Theory 3) (VII Semester)": 4,
  },
  "3-MNC": {
    "Computational Linear Algebra": 4,
    "Probability and Stochastic Process": 3,
    "Data Structures": 4,
    "Elementary Number Theory": 3,
    "Advanced Programming": 3,
    "Discrete Mathematics": 3,
    "Advanced Programming Lab": 1,
    "Data Structures Lab": 1,
  },
  "4-MNC": {
    "Database Systems": 4,
    "Operating Systems": 3,
    "Algebraic Structures": 3,
    "Real Analysis": 3,
    "Mathematical Logic": 3,
    "Vector Analysis and Complex Variables": 3,
    "Operating Systems Lab": 1,
    "Database Systems Lab": 1,
  },
  "5-MNC": {
    "Multivariate Analysis": 3,
    "Database Management Systems": 3,
    "Engineering Economics & Financial Management": 3,
    "Artificial Intelligence": 3,
    "Software Engineering": 4,
    "Software Engineering Lab": 1,
    "Database Management Systems Lab": 1,
  },
  "6-MNC": {
    "Program Elective – 1/Minor Specialization": 3,
    "Program Elective – 2/Minor Specialization": 3,
    "Time Series Analysis": 4,
    "Essentials of Management": 3,
    "Advanced Numerical Methods": 3,
    "Scientific Computing Lab": 1,
  },
  "7-MNC": {
    "Program Elective – 3 / Minor Specialization": 3,
    "Program Elective – 4 / Minor Specialization": 3,
    "Program Elective – 5": 3,
    "Program Elective – 6": 3,
    "Program Elective – 7": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-MNC": {
    "Project Work": 12,
    "Project Work (B Tech – Honors)": 20,
    "B Tech – Honors Theory – 1 (V Semester)": 4,
    "B Tech – Honors Theory – 2 (VI Semester)": 4,
    "B Tech – Honors Theory – 3 (VII Semester)": 4,
  },
  "3-CSFT": {
    "Mathematics for Finance": 4,
    "Programming Paradigm": 4,
    "Algorithms & Data Structures": 4,
    "Introduction to Banking, Payments and Capital Markets": 4,
    "Database Management Systems": 3,
    "Programming Paradigm Lab": 1,
    "Algorithms and Data Structures": 1,
    "Database Management Systems Lab": 1,
  },
  "4-CSFT": {
    "Probability, Stochastic Process and Operations Research": 4,
    "Accounting for Engineers": 3,
    "Cyber Security": 3,
    "Introduction to Fintech": 3,
    "Computer Networks": 3,
    "Financial Management": 3,
    "Fintech Lab": 2,
  },
  "5-CSFT": {
    "Software Application Design": 3,
    "Embedded and Decentralized Finance": 3,
    "Banking Technology": 3,
    "Statistics for Finance": 3,
    "Operating System": 3,
    "Software Application Design Lab": 1,
    "Banking Technology Lab": 1,
  },
  "6-CSFT": {
    "Machine Learning & Deep Learning": 4,
    "Essentials of Management": 3,
    "Capital Markets Technology": 3,
    "Program Elective-1": 3,
    "Program Elective-2": 3,
    "Capital Markets Lab": 1,
    "Machine Learning Lab": 1,
  },
  "7-CSFT": {
    "Program Elective-3": 3,
    "Program Elective-4": 3,
    "Program Elective-5": 3,
    "Program Elective-6": 3,
    "Program Elective-7": 3,
    "Management Research Methods": 3,
  },
  "8-CSFT": {
    "Project Work/Practice School": 12,
  },
  "3-ECE": {
    "Mathematics-III": 3,
    "Analog Electronic Circuits": 4,
    "Network Analysis": 3,
    "Signals & Systems": 3,
    "Digital System Design": 3,
    "Electromagnetic Waves": 3,
    "Digital System Design Lab": 1,
    "Electronic Circuits Lab": 1,
  },
  "4-ECE": {
    "Mathematics-IV": 3,
    "VLSI Design": 4,
    "Digital Signal Processing": 3,
    "Analog Integrated Circuits": 3,
    "Microwave Engineering": 3,
    "Modern Control Theory": 3,
    "VLSI Lab": 1,
    "Electronic System Design Lab": 2,
  },
  "5-ECE": {
    "Engg Economics & Financial Management": 3,
    "Analog and Digital Communication": 4,
    "Microprocessors": 3,
    "Communication Networks": 3,
    "Flexible Core": 3,
    "Digital Signal Processing Lab": 1,
    "Microprocessor Lab": 2,
  },
  "6-ECE": {
    "Essentials of Management": 3,
    "Wireless Communication": 3,
    "Flexible Core": 3,
    "PE – 1 / Minor Specialization": 3,
    "PE – 2 / Minor Specialization": 3,
    "Communication Networks Lab": 1,
    "Communication Systems Lab": 1,
  },
  "7-ECE": {
    "PE – 3 / Minor Specialization": 3,
    "PE – 4 / Minor Specialization": 3,
    "PE – 5": 3,
    "PE – 6": 3,
    "PE – 7": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-ECE": {
    "Project Work": 12,
    "Project Work (B Tech – Honors) (V - VIII sem)": 20,
    "B Tech – Honors Theory – 1 (V semester)": 4,
    "B Tech – Honors Theory – 2 (VI semester)": 4,
    "B Tech – Honors Theory – 3 (VII semester)": 4,
  },
  "3-VLSI": {
    "Engineering Mathematics – III": 3,
    "Analog Circuits": 4,
    "Network Analysis": 3,
    "Signals & Systems": 3,
    "Digital Circuits": 3,
    "Electromagnetic Waves": 3,
    "Digital Circuits Lab": 1,
    "Analog Circuits Lab": 1,
  },
  "4-VLSI": {
    "Engineering Mathematics – IV": 3,
    "Physics of Semiconductor Devices": 4,
    "VLSI Design": 4,
    "Computer Organization and Architecture": 3,
    "FPGA based System Design using Verilog": 3,
    "Digital Signal Processing": 3,
    "FPGA based System Design using Verilog Lab": 1,
    "VLSI Design Lab": 1,
  },
  "5-VLSI": {
    "Engineering Economics and Financial Management": 3,
    "Microcontrollers and Embedded Systems": 3,
    "VLSI Testing": 3,
    "VLSI Fabrication Technology": 3,
    "Verification using System Verilog": 3,
    "Microcontrollers and Embedded Systems Lab": 2,
    "Semiconductor Device and Process Simulation Lab": 1,
  },
  "6-VLSI": {
    "Essentials of Management": 3,
    "Analog and Mixed Signal IC Design": 4,
    "MEMS and NEMS": 3,
    "Program Elective- I (Minor Specialization)": 3,
    "Program Elective- II (Minor Specialization)": 3,
    "Analog IC Design Lab": 1,
    "Semiconductor Fabrication and Characterization Lab": 1,
  },
  "7-VLSI": {
    "Program Elective – III (Minor Specialization)": 3,
    "Program Elective – IV (Minor Specialization)": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-VLSI": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "BTech Honors (Theory 1) (V Sem)": 4,
    "BTech Honors (Theory 2) (VI Sem)": 4,
    "BTech Honors (Theory 3) (VII Sem)": 4,
  },
  "3-ENI": {
    "Engineering Mathematics – III": 3,
    "Analog Electronic Circuits": 4,
    "Digital Circuits & System Design": 4,
    "Networks and Signals": 3,
    "Sensors and Transducers": 3,
    "Linear Control Theory": 3,
    "Digital Circuits and Systems Lab": 1,
    "Sensors and Circuits Lab": 1,
  },
  "4-ENI": {
    "Engineering Mathematics – IV": 3,
    "Linear Integrated Circuits": 3,
    "Microcontrollers": 4,
    "Industrial Instrumentation": 3,
    "Digital Signal Processing": 3,
    "Communication Techniques": 3,
    "Analog Systems Lab": 1,
    "Microcontroller Lab": 1,
  },
  "5-ENI": {
    "Essentials of Management": 3,
    "Industrial Automation & Drives": 4,
    "VLSI Design": 3,
    "Process Instrumentation and Control": 3,
    "Flexible Core – (A1/B1/C1)": 3,
    "Industrial Instrumentation Lab": 1,
    "Process Control Lab": 1,
  },
  "6-ENI": {
    "Engg Economics & Financial Management": 3,
    "Flexible Core – (A2/B2/C2)": 3,
    "Flexible Core – (A3/B3)": 3,
    "PE – 1 / Minor Specialization": 3,
    "PE – 2 / Minor Specialization": 3,
    "Control and Signal Processing Lab": 1,
    "Industrial Automation Lab": 1,
    "Virtual Instrumentation Lab": 1,
  },
  "7-ENI": {
    "PE – 3 / Minor Specialization": 3,
    "PE – 4 / Minor Specialization": 3,
    "PE – 5": 3,
    "PE – 6": 3,
    "PE – 7": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-ENI": {
    "Project Work": 12,
    "Project Work (B Tech – Honors)": 20,
    "B Tech – Honors Theory – 1 (V semester)": 4,
    "B Tech – Honors Theory – 2 (VI semester)": 4,
    "B Tech – Honors Theory – 3 (VII semester)": 4,
  },
  "3-EEE": {
    "Engineering Mathematics – III": 3,
    "Electrical Circuit Analysis": 4,
    "Digital System Design": 3,
    "Electrical Machinery – I": 4,
    "Electromagnetic Field Theory": 3,
    "Microcontrollers": 3,
    "Digital System Design Lab": 1,
    "Microcontroller Lab": 1,
  },
  "4-EEE": {
    "Engineering Mathematics – IV": 3,
    "Analog System Design": 3,
    "Power Electronics": 3,
    "Linear Control Theory": 3,
    "Generation, Transmission & Distribution": 4,
    "Electrical Machinery – II": 3,
    "Analog System Design Lab": 1,
    "Electrical Machinery Lab": 1,
  },
  "5-EEE": {
    "Essentials of Management": 3,
    "Power System Analysis": 4,
    "Digital Signal Processing": 3,
    "Switchgear & Protection": 3,
    "Flexible Core – (A1/B1/C1)": 3,
    "Power Electronics Lab": 1,
    "Systems Simulation Lab": 1,
  },
  "6-EEE": {
    "Engg Economics & Financial Management": 3,
    "Measurements & Instrumentation": 4,
    "Flexible Core – (A2/B2/C2)": 3,
    "PE – 1 / Minor Specialization": 3,
    "PE – 2 / Minor Specialization": 3,
    "Measurements & Instrumentation Lab": 1,
    "Power System Lab": 1,
  },
  "7-EEE": {
    "PE – 3 / Minor Specialization": 3,
    "PE – 4 / Minor Specialization": 3,
    "PE – 5": 3,
    "PE – 6": 3,
    "PE – 7": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-EEE": {
    "Project Work": 12,
    "Project Work (B Tech – Honors)": 20,
    "B Tech – Honors Theory – 1 (V semester)": 4,
    "B Tech – Honors Theory – 2 (VI semester)": 4,
    "B Tech – Honors Theory – 3 (VII semester)": 4,
  },
  "3-CPS": {
    "Engineering Mathematics – III": 3,
    "Analog Electronic Circuits": 3,
    "Digital Logic Design": 3,
    "Computer Architecture and Organization": 3,
    "Data Structures and Algorithms": 4,
    "Sensor Technology": 3,
    "Sensors and Circuits Lab": 1,
    "Data Structures Lab": 1,
  },
  "4-CPS": {
    "Engineering Mathematics – IV": 3,
    "Microcontroller": 3,
    "Digital Transmission": 3,
    "Introduction of Cyber Physical Systems": 3,
    "Introduction to Control Theory": 3,
    "Communication Systems": 3,
    "Communication Systems Lab": 1,
    "Microcontroller Lab": 1,
  },
  "5-CPS": {
    "Essentials of Management": 3,
    "Cyber Physical System Design": 4,
    "Data Communication and Networks": 4,
    "Embedded Systems Design and Programming": 3,
    "Flexible Core – (A1/B1/C1)": 3,
    "Cyber Physical Systems Design Lab": 1,
    "Embedded System Programming Lab": 1,
  },
  "6-CPS": {
    "Engg Economics & Financial Management": 3,
    "Flexible Core – (A2/B2/C2)": 3,
    "Flexible Core – (A3/B3/C3)": 3,
    "PE – 1 / Minor Specialization": 3,
    "PE – 2 / Minor Specialization": 3,
    "CPS Interface Lab": 1,
    "Networking Lab": 1,
  },
  "7-CPS": {
    "PE – 3 / Minor Specialization": 3,
    "PE – 4 / Minor Specialization": 3,
    "PE – 5": 3,
    "PE – 6": 3,
    "PE – 7": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-CPS": {
    "Project Work": 12,
    "Project Work (B Tech – Honors)": 20,
    "B Tech – Honors Theory – 1 (V semester)": 4,
    "B Tech – Honors Theory – 2 (VI semester)": 4,
    "B Tech – Honors Theory – 3 (VII semester)": 4,
  },
  "3-BioMed": {
    "Engineering Mathematics – III": 3,
    "Anatomy and Physiology": 3,
    "Electronics Circuits": 3,
    "Digital System Design": 3,
    "Network Analysis": 3,
    "Signals & Systems": 3,
    "Basic Programming Lab": 1,
    "Electronics Circuits Lab": 2,
  },
  "4-BioMed": {
    "Engineering Mathematics – IV": 3,
    "Basic Clinical Sciences I": 4,
    "Biomedical Instrumentation": 3,
    "Biomechanics": 3,
    "Microcontrollers": 3,
    "Digital Signal Processing": 4,
    "Signal Processing Lab": 1,
    "Microcontroller Lab": 1,
  },
  "5-BioMed": {
    "Engg Economics & Financial Management": 3,
    "Basic Clinical Science II": 4,
    "Medical Devices": 3,
    "Biomaterials": 3,
    "Flexible Core – 1 (A1/B1)": 3,
    "Biomaterials Lab": 1,
    "Biomedical Instrumentation Lab": 1,
  },
  "6-BioMed": {
    "Essentials of Management": 3,
    "Flexible Core – (A2/B2)": 3,
    "Digital Image Processing": 4,
    "Program Elective – I (Minor Specialization)": 3,
    "Program Elective – II (Minor Specialization)": 3,
    "Digital Signal Processing Lab": 1,
    "Digital Image Processing Lab": 1,
  },
  "7-BioMed": {
    "Program Elective – III (Minor Specialization)": 3,
    "Program Elective – IV (Minor Specialization)": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-BioMed": {
    "Project Work": 12,
    "Project Work (B Tech – Honors)": 20,
    "B Tech – Honors Theory – 1 (V semester)": 4,
    "B Tech – Honors Theory – 2 (VI semester)": 4,
    "B Tech – Honors Theory – 3 (VII semester)": 4,
  },
  "3-BioTech": {
    "Engineering Mathematics – III": 3,
    "Biochemistry": 3,
    "Microbiology": 3,
    "Cell and Molecular Biology": 3,
    "Fluid Flow Operations": 3,
    "Bioprocess Calculations": 3,
    "Biochemistry Lab": 1,
    "Microbiology Lab": 2,
  },
  "4-BioTech": {
    "Engineering Mathematics – IV": 3,
    "Chemical and Biochemical Engineering Thermodynamics": 3,
    "Downstream Processes – I": 3,
    "Genetic Engineering": 3,
    "Principles of Heat and Mass Transfer": 3,
    "Immunology": 3,
    "Unit Operations Lab": 2,
    "Molecular Biology and Genetic Engineering Lab": 2,
  },
  "5-BioTech": {
    "Engg Economics & Financial Management": 3,
    "Bioinformatics": 3,
    "Bioprocess Engineering": 3,
    "Bioreaction Engineering": 3,
    "Downstream Processes – II": 3,
    "Bioinformatics Lab": 1,
    "Downstream Processing and Bioprocess Engineering Lab": 2,
  },
  "6-BioTech": {
    "Essentials of Management": 3,
    "Animal and Plant Biotechnology": 3,
    "Bioethics and Intellectual Property Rights": 3,
    "Program Elective – I (Minor Specialization)": 3,
    "Program Elective – II (Minor Specialization)": 3,
    "Bioreaction Engineering and Cell Culture Lab": 2,
    "Modeling and Simulation Lab": 1,
  },
  "7-BioTech": {
    "Program Elective – III (Minor Specialization)": 3,
    "Program Elective – IV (Minor Specialization)": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-BioTech": {
    "Project Work": 12,
    "Project Work (B Tech – Honors)": 20,
    "B Tech – Honors Theory – 1 (V semester)": 4,
    "B Tech – Honors Theory – 2 (VI semester)": 4,
    "B Tech – Honors Theory – 3 (VII semester)": 4,
  },
  "3-MechX": {
    "Engineering Mathematics – III": 3,
    "Data Structures and Algorithms": 3,
    "Digital Design and Verilog Programming": 3,
    "Digital and Analog CMOS Design": 3,
    "Mechanics of Robotics Systems": 3,
    "Sensors and Transducers": 3,
    "Industrial Robotics Lab": 1,
    "Integrated Electronics Lab": 1,
    "Manufacturing Processes Lab": 1,
  },
  "4-MechX": {
    "Engineering Mathematics – IV": 3,
    "Theory of Machines": 3,
    "Design of Machine Elements": 4,
    "Industrial Automation": 3,
    "Linear Control Theory": 3,
    "Microcontroller based System Design": 3,
    "CAD and Kinematics’ Simulation Lab": 1,
    "Microcontroller Lab": 1,
    "Sensors and PLC Lab": 1,
  },
  "5-MechX": {
    "Engg. Economics and Financial Management": 3,
    "Digital Signal Processing": 3,
    "Electric Drives": 4,
    "Manufacturing Technology / Foundations of EV and Hybrid Vehicles": 3,
    "Hydraulics and Pneumatics Systems": 3,
    "Drives, Controls and Modelling Lab": 1,
    "Robot Operating System Lab": 1,
  },
  "6-MechX": {
    "Essentials of Management": 3,
    "Energy and Heat Transfer": 3,
    "Automobile Engineering / Automotive Mechanics for Electric Vehicles": 3,
    "Program Elective – I / Minor Specialization": 3,
    "Program Elective – II / Minor Specialization": 3,
    "Hydraulics Lab": 1,
    "IIoT Lab": 1,
    "Pneumatics Lab": 1,
  },
  "7-MechX": {
    "Program Elective – III / Minor Specialization": 3,
    "Program Elective – IV / Minor Specialization": 3,
    "Program Elective – V": 3,
  },
  "8-MechX": {
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
    "Project Work/Practice School": 12,
    "Project Work (Only for B. Tech. Honors)": 20,
    "BTech Honors (Theory 1)": 4,
    "BTech Honors (Theory 2)": 4,
    "BTech Honors (Theory 3)": 4,
  },
  "3-Aero": {
    "Engineering Mathematics – III": 3,
    "Introduction to Aircraft Structures": 3,
    "Materials and Processing Techniques": 3,
    "Engineering Thermodynamics": 4,
    "Fluid Dynamics": 4,
    "Introduction to Aerospace Engineering": 3,
    "Fluid and Thermal Engineering Lab": 1,
    "Structures Lab": 1,
  },
  "4-Aero": {
    "Engineering Mathematics – IV": 3,
    "Incompressible Aerodynamics": 4,
    "Air-Breathing Propulsion": 3,
    "Linear Control Theory": 3,
    "Aircraft Performance": 3,
    "Advanced Aircraft Structures": 3,
    "Aerodynamics & Propulsion Lab": 1,
    "Numerical Computation Lab": 1,
  },
  "5-Aero": {
    "Engineering Economics and Financial Management": 3,
    "Flexible Core 1": 3,
    "Flight Dynamics and Control": 4,
    "Compressible Aerodynamics": 3,
    "Avionics and Navigation System": 3,
    "Geometric Modelling Lab": 1,
    "Flight Dynamics and Control Lab": 1,
  },
  "6-Aero": {
    "Essentials of Management": 3,
    "Flexible Core 2": 3,
    "Aircraft Design": 4,
    "Program Elective – I / Minor Specialization": 3,
    "Program Elective – II / Minor Specialization": 3,
    "Avionics Lab": 1,
    "Structural Design and Analysis Lab": 1,
  },
  "7-Aero": {
    "Program Elective – III / Minor Specialization": 3,
    "Program Elective – IV / Minor Specialization": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-Aero": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "BTech Honors (Theory 1)": 4,
    "BTech Honors (Theory 2)": 4,
    "BTech Honors (Theory 3)": 4,
  },
  "3-Auto": {
    "Engineering Mathematics – III": 3,
    "Strength of Materials": 3,
    "Materials Science and Metallurgy": 3,
    "Engineering Thermodynamics": 4,
    "Fluid Mechanics": 4,
    "Basics of I C Engines": 3,
    "Geometric Modelling Lab": 1,
    "Automobile Lab – I": 1,
  },
  "4-Auto": {
    "Engineering Mathematics - IV": 3,
    "Automotive Component Design": 4,
    "Manufacturing Techniques & Metrology": 3,
    "Linear Control Theory": 3,
    "Vehicle Transmission Systems": 3,
    "Autotronics": 3,
    "Materials Testing Lab": 1,
    "Automobile Lab – II": 1,
  },
  "5-Auto": {
    "Engineering Economics and Financial Management": 3,
    "Vehicle Chassis Systems": 3,
    "Flexible Core I": 3,
    "Heat Transfer": 4,
    "Electric Vehicle Technology": 3,
    "Simulation Lab": 1,
    "Automobile Lab – III": 1,
  },
  "6-Auto": {
    "Essentials of Management": 3,
    "Vehicle Dynamics and Control": 4,
    "Flexible Core II": 3,
    "Program Elective I/Minor Specialization": 3,
    "Program Elective II/ Minor Specialization": 3,
    "Automotive Design and Analysis Lab": 1,
    "Vehicle Aerodynamics Lab": 1,
  },
  "7-Auto": {
    "Program Elective – III/ Minor Specialization": 3,
    "Program Elective – IV/ Minor Specialization": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor specialization)*": 8,
  },
  "8-Auto": {
    "Project Work/Practice School": 12,
    "Project Work (B.Tech Honors) ": 20,
    "B Tech Honors (Theory 1) (V Semester)": 4,
    "B Tech Honors (Theory 2) (VI Semester)": 4,
    "B Tech Honors (Theory 3) (VII Semester)": 4,
  },
  "3-Mech": {
    "Engineering Mathematics – III": 3,
    "Theory of Machines": 4,
    "Manufacturing Processes-I": 3,
    "Fluid Mechanics": 3,
    "Mechanics of Materials": 3,
    "Thermal Engineering": 4,
    "Computer Aided Mechanical Drawing and Modelling Lab": 1,
    "Workshop Practice - I": 1,
  },
  "4-Mech": {
    "Engineering Mathematics – IV": 3,
    "Design of Machine Elements": 4,
    "Materials Engineering": 3,
    "Metrology and Measurements": 3,
    "Turbomachines": 3,
    "Manufacturing Processes - II": 3,
    "Mechanics Lab": 1,
    "Workshop Practice - II": 1,
  },
  "5-Mech": {
    "Engineering Economics and Financial Management": 3,
    "Flexible Core 1": 3,
    "Geometric Modelling": 3,
    "Finite Element Methods": 3,
    "Heat and Mass Transfer": 4,
    "Mechanical Lab": 1,
    "Metrology Lab": 1,
  },
  "6-Mech": {
    "Essentials of Management": 3,
    "Flexible Core 2": 3,
    "Flexible Core 3": 4,
    "Program Elective – I / Minor Specialization": 3,
    "Program Elective – II / Minor Specialization": 3,
    "Finite Element Methods Lab": 1,
    "Heat Transfer and Solar Energy Lab": 1,
  },
  "7-Mech": {
    "Program Elective – III / Minor Specialization": 3,
    "Program Elective – IV / Minor Specialization": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-Mech": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "BTech Honors (Theory 1)": 4,
    "BTech Honors (Theory 2)": 4,
    "BTech Honors (Theory 3)": 4,
  },
  "3-Industrial": {
    "Engineering Mathematics – III": 3,
    "Industrial Internet of Things": 3,
    "Data Analytics and Visualisation": 3,
    "Control Systems Engineering": 3,
    "3D Printing and Design": 3,
    "Industrial Automation and Robotics": 4,
    "Data Analytics and Visualisation Lab": 1,
    "Automation and Robotics Lab": 1,
  },
  "4-Industrial": {
    "Engineering Mathematics – IV": 3,
    "Operations Research": 4,
    "Work System Engineering and Ergonomics": 3,
    "Supply and Logistics Management": 3,
    "Design of Experiments": 3,
    "Lean Manufacturing and Six Sigma": 4,
    "Work System Engineering and Ergonomics Lab": 1,
    "Computer Aided Operations Research Lab": 1,
  },
  "5-Industrial": {
    "Engineering Economics and Financial Management": 3,
    "Flexible Core 1": 3,
    "Simulation Modeling and Analysis": 3,
    "Total Quality Management": 3,
    "Engineering System Design": 4,
    "Computer Aided Quality Engineering Lab": 1,
    "Simulation Modeling and Analysis Lab": 1,
  },
  "6-Industrial": {
    "Essentials of Management": 3,
    "Flexible Core 2": 3,
    "Operations Management": 4,
    "Program Elective – I / Minor Specialization": 3,
    "Program Elective – II / Minor Specialization": 3,
    "Computer Aided Experimental Design Lab": 1,
    "Computer Aided Operations Management Lab": 1,
  },
  "7-Industrial": {
    "Program Elective – III / Minor Specialization": 3,
    "Program Elective – IV / Minor Specialization": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-Industrial": {
    "Project Work / Practice School": 12,
    "Project Work (B. Tech Honors)": 20,
    "BTech Honors (Theory 1)": 4,
    "BTech Honors (Theory 2)": 4,
    "BTech Honors (Theory 3)": 4,
  },
  "3-Civil": {
    "Engineering Mathematics – III": 3,
    "Fluid Mechanics": 4,
    Surveying: 3,
    "Building Materials": 3,
    "Mechanics of Structures": 4,
    "Water Supply Engineering": 3,
    "Fluid Mechanics Lab": 1,
    "Material Testing Lab": 1,
  },
  "4-Civil": {
    "Engineering Mathematics – IV": 3,
    "Geotechnical Engineering": 3,
    "Transportation Engineering": 4,
    "Basic Reinforced Concrete Design": 3,
    "Wastewater Management": 3,
    "Water Resource Engineering": 3,
    "Surveying Practice": 1,
    "Environmental Engineering Lab": 1,
  },
  "5-Civil": {
    "Essentials of Management": 3,
    "Basic Structural Steel Design": 3,
    "Applied Soil Engineering": 3,
    "Estimation, Costing and Project Management": 4,
    "Flexible Core-I (A1/B1/C1)": 3,
    "Soil Mechanics Lab": 1,
    "Computer Aided Structural Analysis & Design Lab": 1,
  },
  "6-Civil": {
    "Engineering Economics and Financial Management": 3,
    "Flexible Core-II (A2/B2/C2)": 4,
    "Flexible Core-III (A3/B3/C3)": 3,
    "Program Elective –1/ Minor Specialization": 3,
    "Program Elective –2/ Minor Specialization": 3,
    "Building Design and Modelling": 1,
    "Structural Detailing and Drawing": 1,
  },
  "7-Civil": {
    "Program Elective – III/ (Minor Specialization)": 3,
    "Program Elective – IV/ (Minor Specialization)": 3,
    "Program Elective –V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor specialization)*": 8,
  },
  "8-Civil": {
    "Project Work": 12,
    "Project Work (B. Tech Honors) ": 20,
    "B Tech Honors (Theory 1) (V Semester)": 4,
    "B Tech Honors (Theory 2) (VI Semester)": 4,
    "B Tech Honors (Theory 3) (VII Semester)": 4,
  },
  "3-Chem": {
    "Engineering Mathematics – III": 3,
    "Chemical Engineering Thermodynamics": 3,
    "Chemical Process Calculations": 3,
    "Momentum Transfer": 4,
    "Mass Transfer I": 3,
    "Physical and Organic Chemistry": 3,
    "Physical and Organic Chemistry Lab": 1,
    "Mass Transfer Lab": 1,
  },
  "4-Chem": {
    "Engineering Mathematics – IV": 3,
    "Particle Technology": 3,
    "Mass Transfer - II": 3,
    "Chemical Reaction Engineering": 4,
    "Pollution Control and Safety in Chemical Industry": 3,
    "Heat Transfer Operations": 3,
    "Momentum Transfer Lab": 1,
    "Numerical Methods for Chemical Engineers Lab": 1,
  },
  "5-Chem": {
    "Engineering Economics and Financial Management": 3,
    "Process Dynamics and Control": 4,
    "Process Modelling and Simulation": 3,
    "Process Design of Chemical Equipment": 3,
    "Transport Phenomena": 3,
    "Heat Transfer Lab": 1,
    "Mass Transfer Lab": 1,
  },
  "6-Chem": {
    "Essentials of Management": 3,
    "Flexible Core 1 (A1/B1)": 3,
    "Flexible Core 2 (A2/B2)": 4,
    "Program Elective – I / Minor Specialization": 3,
    "Program Elective – II / Minor Specialization": 3,
    "Process Modelling and Simulation Lab": 1,
    "Reaction Engineering and Process Control Lab": 1,
  },
  "7-Chem": {
    "Program Elective – III / Minor Specialization": 3,
    "Program Elective – IV / Minor Specialization": 3,
    "Program Elective – V": 3,
    "Program Elective – VI": 3,
    "Program Elective – VII": 3,
    "Mini Project (Minor Specialization)": 8,
  },
  "8-Chem": {
    "Project Work": 12,
    "Project Work (B. Tech Honors)": 20,
    "BTech Honors (Theory 1)": 4,
    "BTech Honors (Theory 2)": 4,
    "BTech Honors (Theory 3)": 4,
  },
};
export default subjectData;
